### ISSUE TITLE
Portable Mirror

### ISSUE THREAD

**Issue by Nitrous-Fox** [M-oons/VRChat-Mods#11]
I love you portable mirror mod, and know several people that use it. Unfortunately with the last update it no longer works. I'm really missing it, would love to work with you to get it working again.

**Comment by M-oons** [comment]
I transferred ownership of this mod to another modder who has updated it and added features. The latest download of their version of the mod can be found here: https://api.vrcmg.com/v0/mods/197/PortableMirrorMod.dll
