### ISSUE TITLE
Disable showing of clientside objects

### ISSUE THREAD

**Issue by EntityReborn** [M-oons/VRChat-Mods#2]
Objects such as cameras, nameplates, etc, show up in the mirror. This should either be disabled or a togglable item, as often I want to use the mirror for taking pictures.

**Comment by Dervali-git** [comment]
Not the owner of the project, but here's a solution for this issue,

UI/Menu can be disabled by changing the layer mask from
`value = _optimizedMirror ? 263680 : -1025`
to
`value = _optimizedMirror ? 263680 : -5153`

I got the new value from [knah's mod](https://github.com/knah/VRCMods/blob/master/MirrorResolutionUnlimiter) which adds an option for disabling UILayer, UI MenuLayer and, MirrorReflectionLayer in all mirrors.
